name: Remove old artifacts

on:
  schedule:
    # Every 5th day at 5am UTC
    - cron: '0 5 1/5 * *'

jobs:
  remove-old-artifacts:
    if: github.repository == 'automaton-network/automaton-gui'
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - name: Remove old artifacts
      uses: c-hive/gha-remove-artifacts@v1
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        age: '1 day'
        skip-tags: true
